
package Service;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.7-b01 
 * Generated source version: 2.2
 * 
 */
@WebService(name = "OjekOnline", targetNamespace = "http://Service/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface OjekOnline {


    /**
     * 
     * @param arg0
     * @return
     *     returns Service.DataDriver
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "retrieveDriverRating", targetNamespace = "http://Service/", className = "Service.RetrieveDriverRating")
    @ResponseWrapper(localName = "retrieveDriverRatingResponse", targetNamespace = "http://Service/", className = "Service.RetrieveDriverRatingResponse")
    @Action(input = "http://Service/OjekOnline/retrieveDriverRatingRequest", output = "http://Service/OjekOnline/retrieveDriverRatingResponse")
    public DataDriver retrieveDriverRating(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "search_customer_name")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "search_customer_name", targetNamespace = "http://Service/", className = "Service.SearchCustomerName")
    @ResponseWrapper(localName = "search_customer_nameResponse", targetNamespace = "http://Service/", className = "Service.SearchCustomerNameResponse")
    @Action(input = "http://Service/OjekOnline/search_customer_nameRequest", output = "http://Service/OjekOnline/search_customer_nameResponse")
    public String searchCustomerName(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns int
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "saveOrder", targetNamespace = "http://Service/", className = "Service.SaveOrder")
    @ResponseWrapper(localName = "saveOrderResponse", targetNamespace = "http://Service/", className = "Service.SaveOrderResponse")
    @Action(input = "http://Service/OjekOnline/saveOrderRequest", output = "http://Service/OjekOnline/saveOrderResponse")
    public int saveOrder(
        @WebParam(name = "arg0", targetNamespace = "")
        DataOrder arg0);

    /**
     * 
     * @return
     *     returns java.util.List<Service.DataDriver>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "retrieveDrivers", targetNamespace = "http://Service/", className = "Service.RetrieveDrivers")
    @ResponseWrapper(localName = "retrieveDriversResponse", targetNamespace = "http://Service/", className = "Service.RetrieveDriversResponse")
    @Action(input = "http://Service/OjekOnline/retrieveDriversRequest", output = "http://Service/OjekOnline/retrieveDriversResponse")
    public List<DataDriver> retrieveDrivers();

    /**
     * 
     * @param arg0
     * @return
     *     returns int
     */
    @WebMethod(operationName = "update_tabel")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "update_tabel", targetNamespace = "http://Service/", className = "Service.UpdateTabel")
    @ResponseWrapper(localName = "update_tabelResponse", targetNamespace = "http://Service/", className = "Service.UpdateTabelResponse")
    @Action(input = "http://Service/OjekOnline/update_tabelRequest", output = "http://Service/OjekOnline/update_tabelResponse")
    public int updateTabel(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "profileData", targetNamespace = "http://Service/", className = "Service.ProfileData")
    @ResponseWrapper(localName = "profileDataResponse", targetNamespace = "http://Service/", className = "Service.ProfileDataResponse")
    @Action(input = "http://Service/OjekOnline/profileDataRequest", output = "http://Service/OjekOnline/profileDataResponse")
    public String profileData(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns java.util.List<Service.DataHistory>
     */
    @WebMethod(operationName = "search_history")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "search_history", targetNamespace = "http://Service/", className = "Service.SearchHistory")
    @ResponseWrapper(localName = "search_historyResponse", targetNamespace = "http://Service/", className = "Service.SearchHistoryResponse")
    @Action(input = "http://Service/OjekOnline/search_historyRequest", output = "http://Service/OjekOnline/search_historyResponse")
    public List<DataHistory> searchHistory(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns int
     */
    @WebMethod(operationName = "update_locations")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "update_locations", targetNamespace = "http://Service/", className = "Service.UpdateLocations")
    @ResponseWrapper(localName = "update_locationsResponse", targetNamespace = "http://Service/", className = "Service.UpdateLocationsResponse")
    @Action(input = "http://Service/OjekOnline/update_locationsRequest", output = "http://Service/OjekOnline/update_locationsResponse")
    public int updateLocations(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

    /**
     * 
     * @param arg2
     * @param arg1
     * @param arg0
     * @return
     *     returns boolean
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "validate", targetNamespace = "http://Service/", className = "Service.Validate")
    @ResponseWrapper(localName = "validateResponse", targetNamespace = "http://Service/", className = "Service.ValidateResponse")
    @Action(input = "http://Service/OjekOnline/validateRequest", output = "http://Service/OjekOnline/validateResponse")
    public boolean validate(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        String arg2);

}
